import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { ThemeProvider } from '@/components/theme-provider'
import { ThemeModeToggle } from '@/components/theme-mode-toggle'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Rimindify',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{ children: React.ReactNode }>) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <ThemeProvider
                    attribute="class"
                    defaultTheme="system"
                    enableSystem
                    disableTransitionOnChange
                >
                    <section>
                        <ThemeModeToggle />
                    </section>
                    {children}
                </ThemeProvider>
            </body>
        </html>
    )
}
